### PR TITLE
Stake in yearn vault

### PR DESCRIPTION
**Pull request by patcito**
Works like convex staking but for Yearn.
tablestake
stakeinyearn
unstakeyearn

### CODE REVIEW

**Comment by DarkGhost7** [comment]
Maybe put Yearn on top :D

**Comment by antonnell** [comment]
Reeeeeeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaly difficult to for me to check your PRs when you run prettier. Can't check 130 files, where every line has changes.
You can put Yearn on top for now, I'll probably change it to order by APY at some stage when I have accurate APYs though.

Oh, and can you add Yearn APY to it? Similar to how the Curve APY is there.

**Comment by patcito** [comment]
> Reeeeeeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaly difficult to for me to check your PRs when you run prettier. Can't check 130 files, where every line has changes. 

I agree about prettier, that's why the first commit includes prettier changes only. If I may ask though, why do you have a .prettierrc in your project if you don't apply it to you commits? It forces contributors to disable prettier in their editor. You should either enable "prettier on save" in your editor or remove the .prettierrc IMO.

> You can put Yearn on top for now, I'll probably change it to order by APY at some stage when I have accurate APYs though.
> 
> Oh, and can you add Yearn APY to it? Similar to how the Curve APY is there.

Ok I will try to do that.

**Comment by antonnell** [comment]
> If I may ask though, why do you have a .prettierrc in your project if you don't apply it to you commits?

Legacy from when you added it to yearn.fi I belive. I don't start projects from scratch, so things done there are carreid over to here. I'll remove it form the next project if I remember to.

**Comment by patcito** [comment]
> > If I may ask though, why do you have a .prettierrc in your project if you don't apply it to you commits?
> 
> Legacy from when you added it to yearn.fi I belive. I don't start projects from scratch, so things done there are carreid over to here. I'll remove it form the next project if I remember to.

what do you use for formating code in the project? prettier is an industry standard and it saves time for everyone as it picks up the .prettierrc file in the project and there's nothing else to do. Not sure which editors you use but [vscode supports it very easily](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and so does vim and others. I'm open to alternatives such as eslint or what you prefer. I'm fine also if you don't want any formatter. I'll just remember to disable mine.

**Comment by antonnell** [comment]
> > > If I may ask though, why do you have a .prettierrc in your project if you don't apply it to you commits?
> > 
> > 
> > Legacy from when you added it to yearn.fi I belive. I don't start projects from scratch, so things done there are carreid over to here. I'll remove it form the next project if I remember to.
> 
> what do you use for formating code in the project? prettier is an industry standard and it saves time for everyone as it picks up the .prettierrc file in the project and there's nothing else to do. Not sure which editors you use but [vscode supports it very easily](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and so does vim and others. I'm open to alternatives such as eslint or what you prefer. I'm fine also if you don't want any formatter. I'll just remember to disable mine.

I don't use a formatter. One of the benefits of me coding mostly alone - I get to write shit code.

**Comment by patcito** [comment]
> > > > If I may ask though, why do you have a .prettierrc in your project if you don't apply it to you commits?
> > > 
> > > 
> > > Legacy from when you added it to yearn.fi I belive. I don't start projects from scratch, so things done there are carreid over to here. I'll remove it form the next project if I remember to.
> > 
> > 
> > what do you use for formating code in the project? prettier is an industry standard and it saves time for everyone as it picks up the .prettierrc file in the project and there's nothing else to do. Not sure which editors you use but [vscode supports it very easily](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and so does vim and others. I'm open to alternatives such as eslint or what you prefer. I'm fine also if you don't want any formatter. I'll just remember to disable mine.
> 
> I don't use a formatter. One of the benefits of me coding mostly alone - I get to write shit code.

I see where you're coming from but I swear prettier is effortless pretty code, feels like magic really, I use it even on my solo project as there is zero setup, it's just a one time thing in code :D

**Comment by patcito** [comment]
@antonnell is that what you had in mind sir?
yearnapy

**Comment by patcito** [comment]
pushed with prettierrc removed and only 12 lines changes, removed as much prettier as I could. Let me know what you think @antonnell

**Pull request merged**
